### ISSUE TITLE
Paho MQTT callback API version

### ISSUE THREAD

**Issue by am7619** [cyraxx/homematicip-rest-mqtt#4]
With paho-mqtt >2.0 the callback changed ([see here](https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html)).
A quickfix would be to change line 32 in main.py:
`client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1,client_id)`

**Comment by cyraxx** [comment]
Went ahead and upgraded to 2.0 which seems to work fine. Thanks for the pointer!

**Comment by am7619** [comment]
Thank you!
